#!/bin/sh
set -euf

##
# Given a list of numbers, calculate the arithmetic mean a.k.a. average.
#
# Example:
#
#     $ echo "1 2 4" | n-col-mean
#     2.33333
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-09-25
# Version: 1.0.1
##

awk '{
  n = NF
  for (i = 1; i <= n; i++){
    sum += $1
  }
  print sum
}'
