#!/bin/sh
set -euf

##
# Given a list of numbers, calculate the sum of squares.
#
# Example:
#
#     $ echo "1 2 4" | n-col-sumsq
#     16.3333
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-09-25
# Version: 1.0.1
##

awk '{
  n = NF
  split($0,a)

  for (i = 1; i <= n; i++){
    sum += $i
  }
  mean = sum / n

  for (i = 1; i <= n; i++){
    sumsq += (a[i] - mean) ** 2;
  }

  print sumsq
}'
