#!/bin/sh
set -euf

##
# Given a list of numbers, calculate the range.
#
# Example:
#
#     $ echo "1 2 4" | n-col-range
#     3
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-09-25
# Version: 1.0.1
##

awk '{
  min = $1
  max = $1
  for (i = 2; i <= NF; i++){
    if ($i < min) { min = $i }
    if ($i > max) { max = $i }
  }
  range = max - min
  print range
}'
