#!/bin/sh
set -euf -o pipefail

##
# Input a list of numbers, output the arithmetic mean a.k.a. average.
#
# Example:
#
#     $ echo "1\n2\n4" | n-mean
#     2.33333
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

awk '{ sum += $1 }; END { print sum/NR }'
