#!/bin/sh
set -euf

##
# Given a list of numbers, calculate the variance.
#
# Example:
#
#     $ echo "1\n2\n4" | n-row-variance
#     1.55556
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-09-25
# Version: 1.0.1
##

awk '{
  sum += $1
  a[NR] = $1
}
END{
  n = NR
  mean = sum / n
  for (x = 1; x <= n; x++){
    diff += (a[x] - mean) ** 2
  }
  variance = diff / n
  print variance
}'
