#!/bin/sh
set -euf

##
# Given a list of numbers, calculate the maximum.
#
# Example:
#
#     $ echo "1\n2\n4" | n-row-max
#     4
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-09-25
# Version: 1.0.1
##

awk 'NR == 1 || $1 > max { max = $1 } END { print max }'
