#!/bin/sh
set -euf

##
# Input a list of numbers, output the sum.
#
# Example numbers:
#
#     1 2 3
#     4 5 6
#     7 8 9
#
# Example output:
#
#     $ cat numbers | n-sum-fields
#     6
#     15
#     24
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-03-28
##

awk '{ sum = 0; for (i = 1; i <= NF; i++) sum = sum + $i; print sum }'
