#!/bin/sh
set -euf

##
# Given a list of numbers, calculate the minimum.
#
# Example:
#
#     $ echo "1 2 4" | n-col-min
#     1
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-09-25
# Version: 1.0.1
##

awk '{
  min = $1
  for (i = 2; i <= NF; i++){
    if ($i < min) { min = $i }
  }
  print min
}'
