#!/bin/sh
set -euf

##
# Given a list of numbers, calculate the coefficient of variance.
#
# Example:
#
#     $ echo "1 2 4" | n-col-coefficient-of-variance
#     0.534523
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-09-25
# Version: 1.0.1
##

awk '{
  n = NF
  sum = 0
  diff = 0
  for (i = 1; i <= n; i++){
    sum += $i
  }
  mean = sum / n
  for (i = 1; i <= n; i++){
    diff += ($i - mean) ** 2
  }
  variance = diff / n
  standard_deviation = sqrt(variance)
  coefficient_of_variance = standard_deviation / mean
  print coefficient_of_variance
}'
