#!/bin/sh
set -euf

##
# Given a list of numbers, calculate the minimum.
#
# Example:
#
#     $ echo "1\n2\n4" | n-row-min
#     1
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
# Version: 1.0.1
##

awk 'NR == 1 || $1 < min { min = $1 } END { print min }'
