#!/bin/sh
set -euf

##
# Given a list of numbers, calculate the count.
#
# Example:
#
#     $ echo "1 2 4" | n-count
#     3
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-09-25
# Version: 1.0.1
##

awk '{print NF}'
