#!/bin/sh
set -euf

##
# Given a list of numbers, calculate the arithmetic mean a.k.a. average.
#
# Example run:
#
#     $ echo "1\n2\n4" | n-row-mean
#     2.33333
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-09-25
# Version: 1.0.1
##

awk '{ sum += $1 }; END { print sum / NR }'
