#!/bin/sh
set -euf

##
# Given a list of numbers, calculate the standard deviation.
#
# Example:
#
#     $ echo "1\n2\n4" | n-row-standard-deviation
#     1.24722
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-09-25
# Version: 1.0.1
##

awk '{
  sum += $1
  a[NR] = $1
}
END {
  n = NR
  mean = sum / NR
  for (x = 1; x <= NR; x++){
    diff += (a[x] - mean) ** 2
  }
  variance = diff / n
  standard_deviation = sqrt(variance)
  print standard_deviation
}'
