#!/bin/sh
set -euf

##
# Given a list of numbers, calculate the sum of squares.
#
# Example:
#
#     $ echo "1\n2\n4" | n-row-ss
#     4.66667
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-09-25
# Version: 1.0.1
##

awk '{
  sum += $i
  a[NR] = $1
}
END {

awk '{
  n = NR
  mean = sum / n

  for (i = 1; i <= n; i++){
    ss += (a[i] - mean) ^ 2;
  }

  print ss
}'
