#!/bin/sh
set -euf

##
# Input a list of numbers, output the median.
#
# Example:
#
#     $ echo "1\n2\n4" | n-median
#     2
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

sort -n |
awk '{ a[NR] = $1 }
END {
  if (NR % 2) {
    median = a[(NR + 1) / 2];
  } else {
    median = (a[(NR / 2)] + a[(NR / 2) + 1]) / 2.0;
  }
  print median
}'
