#!/bin/sh
set -euf

##
# Input a list of numbers, output the minimum value.
#
# Example:
#
#     $ echo "1\n2\n4" | n-min
#     1
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

awk 'NR == 1 || $1 < min { min = $1 } END { print min }'
