#!/bin/sh
set -euf

##
# Given a list of numbers, calculate the range.
#
# Example:
#
#     $ echo "1\n2\n4" | n-range
#     3
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-09-25
# Version: 1.0.1
##

awk '
NR == 1 {
  min = $1
  max = $1
}
{
  if ($1 < min) { min = $1 }
  if ($1 > max) { max = $1 }
}
END {
  range = max - min
  print range
}'
